version: "3.9"

networks:
  backend:

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: nilondes
      POSTGRES_PASSWORD: tele_test
      POSTGRES_DB: cash_register

    volumes:
      - /var/lib/postgresql/data
    networks:
      - backend
  app:
    build:
      context: .
      args:
        DEPS: dev
    ports:
      - "8000:8000"
    environment:
      DEBUG: "true"
      DATABASE_USER: nilondes
      DATABASE_PASSWORD: tele_test
      DATABASE_DB: cash_register
      DATABASE_HOST: postgres
    networks:
      - backend