# Generated by Django 5.1.6 on 2025-03-02 11:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_check_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitems',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkitems',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
