# Generated by Django 5.1.6 on 2025-03-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_checkitems_amount_checkitems_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='file_path',
            field=models.FilePathField(path='media/'),
        ),
    ]
