# Generated by Django 5.1.6 on 2025-03-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_check_file_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckItems',
            new_name='CheckItem',
        ),
    ]
